### ISSUE TITLE
Feature request: Read time when shop will have goods

### ISSUE THREAD

**Issue by liudger** [MaxWinterstein/toogoodtogo-ha-mqtt-bridge#101]
Nowadays the shop will tell the time when products will be available. It would be useful to be aware of this and have intense polling start on this time. 

![IMG_3188](https://user-images.githubusercontent.com/4112111/199671705-fd81bebc-610c-425e-9af8-4e84b9d9447d.jpeg)

**Comment by Dielee** [comment]
@MaxWinterstein what do you think about this? Maybe it's a good idea, but enable intense fetch for every favorite may lead to an api ban. If this should be possible, there has to be an option to auto enable intense fetch per favorite. Maybe I will create a branch to test some options in the next days.

**Comment by liudger** [comment]
Maybe it could also be option when we have the time that a minute before we send a notification. As we know the time so it doesn't wait.

**Comment by liudger** [comment]
I try to take a look today.

**Comment by Dielee** [comment]
@liudger Does this work as expected ?

**Comment by liudger** [comment]
I didn't have time yet. I am sorry. If you could leave it open a bit. I think I got some time soon.

**Comment by Dielee** [comment]
Merged with #105
