### ISSUE TITLE
URL for buy directly

### ISSUE THREAD

**Issue by liudger** [MaxWinterstein/toogoodtogo-ha-mqtt-bridge#102]
Is there a way to check the link for the buy button?  This way home assistant can send a notification directly with the buy option triggered. now you have to click 2 buttons before you can buy.

**Comment by liudger** [comment]
Yeah I mean the link generated from the data object directs to the landing page of the store. My question would be that it directs it a bit further. So the reserve option is already pressed and you only have to click pay.

**Comment by MaxWinterstein** [comment]
Well, I am not sure if this "deep link" exists, that already like pressed the buy button.

Technically some automatic buying process is possible, but in my opinion, this goes too far into things that toogoodtogo might not like. And I don't want to test how thin the ice is.

I need to draw a line somewhere, and I guess this is the place. Sorry.

/close
