### ISSUE TITLE
Error message in the log

### ISSUE THREAD

**Issue by HanBarn** [MaxWinterstein/toogoodtogo-ha-mqtt-bridge#115]
Today I have noticed the Add-on stopped.
Checked the log and found the following error messages.
Not sure if this is a new error.
To make sure it is not related to HA I have updated HA to the latest version.
My HA was from December.
The Add-on is running again but still some messages in the log.
Not sure the TGTG shops will be available in HA, at this moment the favorite shops have no boxes.
The TGTG app on my smartphone is working fine so there is no TGTG error.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: TooGoodToGo Home Assistant MQTT Bridge
 Publish TooGoodToGo stock as MQTT messages
-----------------------------------------------------------
 Add-on version: 2.4.0.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.4  (amd64 / generic-x86-64)
 Home Assistant Core: 2023.1.5
 Home Assistant Supervisor: 2022.12.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] toogoodtogo-ha-mqtt-bridge.sh: executing... 
[11:05:31] INFO: Copy settings file
Saved tokens found.
If you have any problems reinstalling the add-on might help.
[cont-init.d] toogoodtogo-ha-mqtt-bridge.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[11:05:31] INFO: Strating Bridge...
2023-01-18 11:05:32 [INFO] Connecting mqtt
2023-01-18 11:05:32 [INFO] Starting loop
2023-01-18 11:05:32 [INFO] Checking latest tgtg appstore version
2023-01-18 11:05:32 [INFO] Loaded tokens form tokenfile. Logging in with tokens.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/toogoodtogo_ha_mqtt_bridge/main.py", line 294, in fetch_loop
    tgtg_client.login()
  File "/usr/local/lib/python3.8/site-packages/tgtg/__init__.py", line 136, in login
    self._refresh_token()
  File "/usr/local/lib/python3.8/site-packages/tgtg/__init__.py", line 126, in _refresh_token
    raise TgtgAPIError(response.status_code, response.content)
tgtg.exceptions.TgtgAPIError: (403, b'<html><head><title>apptoogoodtogo.com</title><style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style></head><body style="margin:0"><p id="cmsg">Please enable JS and disable any ad blocker</p><script data-cfasync="false">var dd={\'rt\':\'c\',\'cid\':\'AHrlqAAAAAMA7gIzSGf-EOEAVlrTzA==\',\'hsh\':\'1D42C2CA6131C526E09F294FE96F94\',\'t\':\'fe\',\'r\':\'b\',\'s\':35558,\'e\':\'d26833a3777d6fc4f9953b336af464281b207a965b9459361f2817d73a5d1950\',\'host\':\'geo.captcha-delivery.com\'}</script><script data-cfasync="false" src="https://ct.captcha-delivery.com/c.js"></script></body></html>\n')

**Comment by HanBarn** [comment]
Searched for the error and found an issue it might be related.
My polling interval is usually set on 5 minutes sometimes 2 minutes.
I am using this for many weeks now without any problems until today.
Yesterday and the days before were fine.
So an IP ban is not very likely.

Found this:
https://github.com/ahivert/tgtg-python/issues/205

**Comment by mupsje** [comment]
Same here indeed...
Any update ?

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/toogoodtogo_ha_mqtt_bridge/main.py", line 294, in fetch_loop
    tgtg_client.login()
  File "/usr/local/lib/python3.8/site-packages/tgtg/__init__.py", line 136, in login
    self._refresh_token()
  File "/usr/local/lib/python3.8/site-packages/tgtg/__init__.py", line 126, in _refresh_token
    raise TgtgAPIError(response.status_code, response.content)
tgtg.exceptions.TgtgAPIError: (403, b'<html><head><title>apptoogoodtogo.com</title><style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style></head><body style="margin:0"><p id="cmsg">

Please enable JS and disable any ad blocker</p>

<script data-cfasync="false">var dd={\'rt\':\'c\',\'cid\':\'AHrlqAAAAAMAm2KLn2YPWxcAVGllUw==\',\'hsh\':\'1D42C2CA6131C526E09F294FE96F94\',\'t\':\'fe\',\'r\':\'b\',\'s\':35558,\'e\':\'5c21239735f93b9dbbfe19b270586e464632ab28a6dd9b8910a2cf13c8baa66f\',\'host\':\'geo.captcha-delivery.com\'}</script><script data-cfasync="false" src="https://ct.captcha-delivery.com/c.js"></script></body></html>\n')

**Comment by bigbasti** [comment]
Same here... Started to fail some time yesterday I think. 
Maybe there was an API change at tgtg?

**Comment by HanBarn** [comment]
> Same here... Started to fail some time yesterday I think.
> Maybe there was an API change at tgtg?

It must be something we have in common.
The above issue #205 contains a link to some changed code.
I am lacking knowledge but it might be helpful for the developers of the code.
https://github.com/ahivert/tgtg-python/issues/205#issuecomment-1396271968

**Comment by mupsje** [comment]
I think @MaxWinterstein  is busy with it...
We have to wait.   ;)

**Comment by mupsje** [comment]
Still no fix?

**Comment by MaxWinterstein** [comment]
Finally found a few minutes for this issue. 

Well, seems bad. Will jump on the train at the `tgtg-python` repo, and try my best.

**Comment by MaxWinterstein** [comment]
@Dielee I came across https://github.com/ahivert/tgtg-python/pull/208 - which seems like a good start on that. 

Did you go further with this idea? Did you make any use of the mentioned cookie here? https://github.com/ahivert/tgtg-python/issues/205#issuecomment-1399608570

**Comment by MaxWinterstein** [comment]
So, everyone, the update should be available now, pls have a try!

A new login is needed, check your email for the approvals.

**Comment by bigbasti** [comment]
Log is looking good again, thanks for the quick fix and anjoy the kofi :)

**Comment by SLG** [comment]
Same here! Thanks!

**Comment by MaxWinterstein** [comment]
Glad to hear it is working!

Thanks 4 the kofi ❤️

**Comment by mupsje** [comment]
Thanks , and indeed working,!
