### ISSUE TITLE
Feature Request: Turn off all polling via sensor

### ISSUE THREAD

**Issue by fsa317** [MaxWinterstein/toogoodtogo-ha-mqtt-bridge#119]
There are times where I would like to easily shut off all polling without changing the cron yaml.  It would be cool if we could have another sensor / setting that is easily controlled (like the intense switch) for all polling.

**Comment by MaxWinterstein** [comment]
This was already discussed somewhere, but I cant find it.

The best way for this might be to just use a service call

```
service: hassio.addon_stop
data:
  addon: f1c878cb_tgtg-ha-mqtt-bridge
```

I am sure there is an nice way to create a switch to start/stop it.

**Comment by fsa317** [comment]
This is perfectly fine!  Thanks.

**Comment by MaxWinterstein** [comment]
For reference, this was discussed here:

https://github.com/MaxWinterstein/homeassistant-addons/issues/5

Mentioned issue with underscore has already been fixed.
