### ISSUE TITLE
Addon blocked??

### ISSUE THREAD

**Issue by DavyRoswinkel** [MaxWinterstein/toogoodtogo-ha-mqtt-bridge#13]
Add-on version: 1.6.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.4  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.9.7
 Home Assistant Supervisor: 2021.09.6

Getting the following error:

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "toogoodtogo_ha_mqtt_bridge/main.py", line 148, in loop
    if not check():
  File "toogoodtogo_ha_mqtt_bridge/main.py", line 32, in check
    shops = tgtg_client.get_items(page_size=400)
  File "/usr/local/lib/python3.8/site-packages/tgtg/__init__.py", line 143, in get_items
    self._login()
  File "/usr/local/lib/python3.8/site-packages/tgtg/__init__.py", line 122, in _login
    raise TgtgLoginError(response.status_code, response.content)
tgtg.exceptions.TgtgLoginError: (403, b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">\n<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">\n<TITLE>ERROR: The request could not be satisfied 403 ERROR The request could not be satisfied.Request blocked.We can\'t connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n<BR clear="all">\nIf you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.Generated by cloudfront (CloudFront)\nRequest ID: 2YPoLcrAGakoI2rN8RVc37PUlxVXH43wjHYs5v7GiWJSzDyTo7uc9A==\n</PRE>\n<ADDRESS>\n</ADDRESS>\n</BODY></HTML>')
---------------------------------------------------------------------------------------------------
Config:
mqtt:
  host: *******
  port: 1883
  username: ******
  password: ******
tgtg:
  email: ******
  password: ******
  every_n_minutes: 10
timezone: Europe/Berlin
locale: en_us
cleanup: true

------------------------------------------------------------------------------------------------------
Does anyone know how to solve this???

**Comment by MaxWinterstein** [comment]
thanks for the hint!

The problem is based on the library I use. I already provided some PR to get it fixed. (see https://github.com/ahivert/tgtg-python/issues/108).

As soon as it gets merged I will upgrade the add-on.

**Comment by DavyRoswinkel** [comment]
> 
> 
> thanks for the hint!
> 
> The problem is based on the library I use. I already provided some PR to get it fixed. (see [ahivert/tgtg-python#108](https://github.com/ahivert/tgtg-python/issues/108)).
> 
> As soon as it gets merged I will upgrade the add-on.

Looking forward to the upgrade
Will close this issue as soon as it's solved....
Thanks again and have a nice day

**Comment by MaxWinterstein** [comment]
As https://github.com/ahivert/tgtg-python did not release the fix within a new version I fixed it here myself.

Update is available, please test.

**Comment by DavyRoswinkel** [comment]
> As https://github.com/ahivert/tgtg-python did not release the fix within a new version I fixed it here myself.
> 
> Update is available, please test.

It works!
Logfiles show as they should. Problem solved!
Thanks again for solving issues so quickly.
