### ISSUE TITLE
tgtg.exceptions.TgtgAPIError: (404, b'{"type":"about:blank","title":"Not Found","status":404,"detail":"No static resource auth/v3/token/refresh.","instance":"/api/auth/v3/token/refresh"}')

### ISSUE THREAD

**Issue by huizebruin** [MaxWinterstein/toogoodtogo-ha-mqtt-bridge#175]
today i got this error.

``` Add-on: TooGoodToGo Home Assistant MQTT Bridge
 Publish TooGoodToGo stock as MQTT messages
-----------------------------------------------------------
 Add-on version: 2.5.1.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.2  (amd64 / generic-x86-64)
 Home Assistant Core: 2024.11.3
 Home Assistant Supervisor: 2024.11.4
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/toogoodtogo-ha-mqtt-bridge.sh
[19:51:24] INFO: Copy settings file
Saved tokens found.
If you have any problems reinstalling the add-on might help.
cont-init: info: /etc/cont-init.d/toogoodtogo-ha-mqtt-bridge.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun toogoodtogo-ha-mqtt-bridge (no readiness notification)
s6-rc: info: service legacy-services successfully started
[19:51:24] INFO: Strating Bridge...
2024-11-22 19:51:28 [INFO] Connecting mqtt
2024-11-22 19:51:28 [INFO] Starting loop
2024-11-22 19:51:28 [INFO] Checking latest tgtg appstore version
2024-11-22 19:51:29 [INFO] Loaded tokens form tokenfile. Logging in with tokens.
Exception in thread Thread-3 (fetch_loop):
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/app/toogoodtogo_ha_mqtt_bridge/main.py", line 324, in fetch_loop
    tgtg_client.login()
  File "/usr/local/lib/python3.11/site-packages/tgtg/__init__.py", line 139, in login
    self._refresh_token()
  File "/usr/local/lib/python3.11/site-packages/toogoodtogo_ha_mqtt_bridge-2.2.3-py3.11.egg/toogoodtogo_ha_mqtt_bridge/mytgtgclient.py", line 61, in _refresh_token
    raise TgtgAPIError(response.status_code, response.content)
tgtg.exceptions.TgtgAPIError: (404, b'{"type":"about:blank","title":"Not Found","status":404,"detail":"No static resource auth/v3/token/refresh.","instance":"/api/auth/v3/token/refresh"}')
```
How can i fix this , must i reinstall the addon?

**Comment by MaxWinterstein** [comment]
I guess this is related to some update of TGTG itself. Will update this soon.

Rel https://github.com/ahivert/tgtg-python/releases/tag/0.18.0 

Rel https://github.com/ahivert/tgtg-python/pull/324

**Comment by MaxWinterstein** [comment]
So I just finished a big rewrite here, something I postponed way too long.

Along all the nice stuff that makes this project way better to work on, I updated the dependencies so it should work again. 

The plain docker version works fine, next step is to adjust the addon that wraps this. Hope to get this done also the next days.

**Comment by elyobelyob** [comment]
Hi, thanks for this. I notice v3.0.0 was released 14 hours ago. I seem to be stuck on v2.5.1.3 and don't see an update this package within Add-On page. I've run the 'check for updates', but no change. Wary of completely re-installing, but will if that's the route needed.

Thanks for advice

**Comment by HanBarn** [comment]
> So I just finished a big rewrite here, something I postponed way too long.
> 
> Along all the nice stuff that makes this project way better to work on, I updated the dependencies so it should work again.
> 
> The plain docker version works fine, next step is to adjust the addon that wraps this. Hope to get this done also the next days.

Thanks Max!
Does this mean we can’t update the current release from the Add On within Home Assistant yet to version 3.0.0 ?

**Comment by MaxWinterstein** [comment]
> Does this mean we can’t update the current release from the Add On within Home Assistant yet to version 3.0.0 ?

Yes, I need to create the update of the add-on itself.

It is in progress at https://github.com/MaxWinterstein/homeassistant-addons/pull/282, and so far it seems to work.

**Comment by MaxWinterstein** [comment]
I just released an update to the Add-On, pls test 🙃

**Comment by HanBarn** [comment]
> I just released an update to the Add-On, pls test 🙃

First test shows no problems, at this moment my favorite shops have no boxes but the history chart in HA is updated.
No more errors in the log.
Only thing is the old tokens need to be updated so the e-mail from TGTG needs to be approved by logging in.

Thanks again for your update!

**Comment by LJ-Stevo** [comment]
I see following in lo after, I logged in succesfully via webbrowser on phone.
Captcha??

[12:12:30] INFO: Strating Bridge...
2024-11-28 12:12:32 [INFO] Connecting mqtt
2024-11-28 12:12:32 [INFO] Starting loop
2024-11-28 12:12:32 [INFO] Logging in with credentials
2024-11-28 12:12:32 [DEBUG] MQTT seems connected. (reason_code: Success)
Exception in thread Thread-2 (fetch_loop):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/app/toogoodtogo_ha_mqtt_bridge/main.py", line 307, in fetch_loop
    tgtg_client.login()
  File "/app/.venv/lib/python3.12/site-packages/tgtg/__init__.py", line 173, in login
    raise TgtgLoginError(response.status_code, response.content)
tgtg.exceptions.TgtgLoginError: (403, b'{"url":"https://geo.captcha-delivery.com/captcha/?initialCid=AHrlqAAAAAMA-VNmpzcyQKsAThb1hw==&cid=Gt82c426WIt4oc1r8okpeaN90uHkRJjXv9NlDyjlVLi~gUIU0VXbjsmZduqeEn5T~_XaObwcF~6Y79N3o8mYwLkGT8c9xKuYdr8Y4UBsmIhcV3_XhKiovdfzLEaHCLys&referer=https%3A%2F%2Fapptoogoodtogo.com%2Fapi%2Fauth%2Fv5%2FauthByEmail&hash=1D42C2CA6131C526E09F294FE96F94&t=fe&s=35587&e=5415bf9d2c50b2d8e2ed247fabe4910e8881d39d6305e6ae754f37d1ade67c03"}')

**Comment by LJ-Stevo** [comment]
> Rel: #214
> 
> @LJ-Stevo and others:
> 
> Did you have the addon auto-restarting before?

I don't know I understand the question, but the "start at boot", "Watchdog" and "auto update" is turned on.
I also did a fresh install and restarted the add-on several times. But my IP seems to be blocked and I cannot change it (BE - Telenet)
A friendly man on discord tells me to turn off the add-on for a day... Hope it helps.
If you have an other work around, please let me know. I just have this for a week, and I was so excited to have it working, but now I have a sad face... (also replayed on the other same open issue.

**Comment by MaxWinterstein** [comment]
> I don't know I understand the question, but the "start at boot", "Watchdog" and "auto update" is turned on.

Yes, thanks for looking that up. I guess the "Watchdog" kept the addon restarting which _Datadome_ found not nice and started to throw you on the "block" list.

As written in #214 - not much I can do here for you. Sorry.

I am going to close this here, as the issue itself is resolved.

---

Btw, I am deeply touched to see that there are people out in the wild that use this little thing I made. This is awesome. Thanks ❤️
