### ISSUE TITLE
Feature request: nicer MQTT discovery

### ISSUE THREAD

**Issue by poudenes** [MaxWinterstein/toogoodtogo-ha-mqtt-bridge#21]
Hi,

Would it be nicer to add:

```
"device": {"identifiers": "toogood_togo","name": "Toogood To Go","manufacturer": "MaxWinterstein"},
```

to the discovery part?

When you have this all entities will be combine together as a "Device" and when you click on the name you see all the entities.

Its a glitch upgrade :)

Then you will get this (example) 
<img width="1057" alt="Screenshot 2021-11-18 at 12 14 36" src="https://user-images.githubusercontent.com/4399532/142405344-a719a9e5-681d-4421-9f18-f7f95d48e5ea.png">

Upper left you see then: Toogood To Go.
Below you see then "by MaxWinterstrein"
And richt the entities in a list.

**Comment by DavyRoswinkel** [comment]
Nice but it would be even nicer if it worked......Stopped working here, and I think there will not be a solution in the near future. 
It was such a nice job Max did...

**Comment by poudenes** [comment]
What I know (tried myself) delete the entities and add them clear. It will work. Rest of the discovery will be the same.
Only this will add so it will become under "device"...

**Comment by poudenes** [comment]
Maybe create a beta version and try. I would open to help. Create a test HA and see how this will work.
```
                {
                    "name": f"TooGoodToGo - {shop['display_name']}",
                    "icon": "mdi:food" if stock > 0 else "mdi:food-off",
                    "state_topic": f"homeassistant/sensor/toogoodtogo_{item_id}/state",
                    "json_attributes_topic": f"homeassistant/sensor/toogoodtogo_{item_id}/attr",
                    "unit_of_measurement": "portions",
                    "value_template": "{{ value_json.stock }}",
                    "unique_id": f"toogoodtogo_{item_id}",
                }
```
to:
```
                {
                    "name": f"TooGoodToGo - {shop['display_name']}",
                    "icon": "mdi:food" if stock > 0 else "mdi:food-off",
                    "device": {"identifiers": "toogood_togo","name": "Toogood To Go","manufacturer": "MaxWinterstein"},
                    "state_topic": f"homeassistant/sensor/toogoodtogo_{item_id}/state",
                    "json_attributes_topic": f"homeassistant/sensor/toogoodtogo_{item_id}/attr",
                    "unit_of_measurement": "portions",
                    "value_template": "{{ value_json.stock }}",
                    "unique_id": f"toogoodtogo_{item_id}",
                }
```

**Comment by MaxWinterstein** [comment]
Open to these changes, but sadly can't test it easily as I suffer from the blocked IP issue too...

**Comment by poudenes** [comment]
Same issue here now also :(

**Comment by MaxWinterstein** [comment]
Having all these entities group under one device makes sense to me.

But it seems there is more needed than just this one line? I guess somewhere here:

https://github.com/MaxWinterstein/toogoodtogo-ha-mqtt-bridge/blob/132d88f91703ec4b547374a2711781ed89c5b3e6/toogoodtogo_ha_mqtt_bridge/main.py#L58

But out of time for today :(

**Comment by TerrorSource** [comment]
@MaxWinterstein how did you get the ip blocked?

I know the time slots for the favorite tgtg stores so im going to try to run the add-on only in the known timeslots, interval of 1 minute so only 60 polls a day

**Comment by TerrorSource** [comment]
@niklas1375 i made 2 automations in HomeAssistant, 1 to start and 1 to stop.

Start:
``alias: tgtg-start
description: ''
trigger:
  - platform: time
    at: '17:00'
condition: []
action:
  - service: hassio.addon_start
    data:
      addon: f1c878cb_tgtg-ha-mqtt-bridge
mode: single
``

**Comment by Dielee** [comment]
This function is now released. Version > 2.0.0 includes the new feature.
