### ISSUE TITLE
After update not working Captcha Failing

### ISSUE THREAD

**Issue by mupsje** [MaxWinterstein/toogoodtogo-ha-mqtt-bridge#214]
[10:36:36] INFO: Copy settings file
No saved tokens found.
Please make sure to check your email for the login request and answer quickly.
You can't open it on a mobile phone where the TGTG app itself is installed.
cont-init: info: /etc/cont-init.d/toogoodtogo-ha-mqtt-bridge.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun toogoodtogo-ha-mqtt-bridge (no readiness notification)
[10:36:36] INFO: Strating Bridge...
s6-rc: info: service legacy-services successfully started
2024-11-28 10:36:37 [INFO] Connecting mqtt
2024-11-28 10:36:37 [INFO] Starting loop
2024-11-28 10:36:37 [INFO] Logging in with credentials
2024-11-28 10:36:37 [DEBUG] MQTT seems connected. (reason_code: Success)
Exception in thread Thread-2 (fetch_loop):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/app/toogoodtogo_ha_mqtt_bridge/main.py", line 307, in fetch_loop
    tgtg_client.login()
  File "/app/.venv/lib/python3.12/site-packages/tgtg/__init__.py", line 173, in login
    raise TgtgLoginError(response.status_code, response.content)
tgtg.exceptions.TgtgLoginError: (403, b'{"url":"https://geo.captcha-delivery.com/captcha/?initialCid=AHrlqAAAAAMAXPH4I5w-XvwAVGllUw==&cid=TB82FkBcpn2WNXtZKrqGmVbd2aNP0RhaYZ3xyiXVtOyOWK4xyDKYN5eNXEuYf4qcUp5gt6PnqFjT7TTLGuho6Q9CTEhuYAJhDSg9qwuGerSUv8CNfTZ5uxDRtAo8DoPf&referer=https%3A%2F%2Fapptoogoodtogo.com%2Fapi%2Fauth%2Fv5%2FauthByEmail&hash=1D42C2CA6131C526E09F294FE96F94&t=fe&s=35587&e=f13351212ec4490113d8a25deee0031db75f380b5ed0db98377e24c9edda7933"}')

**Comment by HanBarn** [comment]
Did you check your e-mail?
There should be an email from TGTG which ask you to login.

**Comment by elyobelyob** [comment]
Same issue. Have clicked the email on my desktop computer with no issue.

**Comment by MaxWinterstein** [comment]
This captcha thing is pretty old, see e.g. https://github.com/ahivert/tgtg-python/issues/247

It is based on some security system of toogoodtogo, called datadome. Sometimes you can see it on the mobile phone with a popup and the 'Verify you are human' thing.

For some users simply reconnecting the Internet Connection helps, as it changes the IP address.

Did you have the old addon auto-restarting? As far as I remember this captcha thing is mostly triggered by having to many requests.

**Comment by mupsje** [comment]
Yes, indeed

The app did not react to the captcha, so I did a fresh install, received a email now.
 
 Now I get "Failed to get f1c878cb_tgtg-ha-mqtt-bridge logs, network error"
 
 [13:44:08] INFO: Strating Bridge...
s6-rc: info: service legacy-services successfully started
2024-11-28 13:44:10 [INFO] Connecting mqtt
2024-11-28 13:44:10 [INFO] Starting loop
2024-11-28 13:44:10 [INFO] Logging in with credentials
2024-11-28 13:44:10 [DEBUG] MQTT seems connected. (reason_code: Success)
2024-11-28 13:44:26 [INFO] Written tokens.json file to filesystem
2024-11-28 13:44:26 [INFO] Next run at 2024-11-28 13:50:14
s6-rc: info: service legacy-services: stopping
if: fatal: unable to spawn s6-test: No such file or directory
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/toogoodtogo-ha-mqtt-bridge.sh
[13:44:57] INFO: Copy settings file
Saved tokens found.
If you have any problems reinstalling the add-on might help.
cont-init: info: /etc/cont-init.d/toogoodtogo-ha-mqtt-bridge.sh exited 0
s6-rc: info: service legacy-cont-init successfully started

**Comment by mupsje** [comment]
Ahhh , this is a SSL problem

I run a cloudflare tunnel, when I'm looking at the local address I get :

[13:49:31] INFO: Copy settings file
Saved tokens found.
If you have any problems reinstalling the add-on might help.
cont-init: info: /etc/cont-init.d/toogoodtogo-ha-mqtt-bridge.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun toogoodtogo-ha-mqtt-bridge (no readiness notification)
[13:49:31] INFO: Strating Bridge...
s6-rc: info: service legacy-services successfully started
2024-11-28 13:49:32 [INFO] Connecting mqtt
2024-11-28 13:49:32 [INFO] Starting loop
2024-11-28 13:49:32 [DEBUG] MQTT seems connected. (reason_code: Success)
2024-11-28 13:49:32 [INFO] Checking latest tgtg appstore version
2024-11-28 13:49:33 [INFO] Loaded tokens form tokenfile. Logging in with tokens.
2024-11-28 13:49:33 [INFO] Next run at 2024-11-28 14:00:00

**Comment by mupsje** [comment]
yes sir

language: nl-NL
polling_schedule: "*/10 * * * *"
intense_fetch_interval: 30
intense_fetch_period_of_time: 5

It working now, 

But I would like to mention that you need to take a look at the SSL part of code.

Because now I only can view the logs local Ip address , and not through my Cloudflare tunnel https addres
Before we where able to watch it from SSL

![image](https://github.com/user-attachments/assets/931dde71-b6cc-462a-b0ad-fa3b981b5411)

or do I have a inside problem?

**Comment by MaxWinterstein** [comment]
> or do I have a inside problem

Those log viewer is delivered by home assistant itself, I have no relation to it. 

Vte, I am using cloudflare tunnel (via addon) myself, logs work fine for me.

**Comment by mupsje** [comment]
mmmm, thats going to be nightwork again :(

Thanks for the help

**Comment by LJ-Stevo** [comment]
> This captcha thing is pretty old, see e.g. [ahivert/tgtg-python#247](https://github.com/ahivert/tgtg-python/issues/247)
> 
> It is based on some security system of toogoodtogo, called datadome. Sometimes you can see it on the mobile phone with a popup and the 'Verify you are human' thing.
> 
> For some users simply reconnecting the Internet Connection helps, as it changes the IP address.
> 
> Did you have the old addon auto-restarting? As far as I remember this captcha thing is mostly triggered by having to many requests.

I cannot change my IP adress.
I did a fresh install, but, it remains the same issue... (captcha)
Sometimes I recieve a mail, but it takes a while before I get them, and if I have a mail, the link is then too old.
When I run de url of Captcha, it says I'm blocked.

**Comment by MaxWinterstein** [comment]
In general, and if I remember correctly, the only two options are

- waiting and keeping all addons/devices chill until the IP gets unblocked (no idea how long this takes, I assume some days - I have had this issue before, too)
- get a new IP address (not possible in some situations, I know)

I am going to close this here, as the issue itself is resolved. 


---

Btw, I am deeply touched to see that there are people out in the wild that use this little thing I made. This is awesome. Thanks ❤️
