### ISSUE TITLE
Only shows 10 stores

### ISSUE THREAD

**Issue by SteGe88** [MaxWinterstein/toogoodtogo-ha-mqtt-bridge#38]
I have more than 10 stores marked as favorite, and despite some tries (remove known stores, remove token to re-connect) I don't get more than 10 stores in my new list of known stores and in Home-Assistant. Also in a MQTT explorer I only see those 10 stores.

Is there a limit on 10 stores, and if so, how can I adjust this to have more stores available in HA?

**Comment by DavyRoswinkel** [comment]
> 
> 
> Is there a limit on 10 stores, and if so, how can I adjust this to have more stores available in HA?

I guess it's not a limit as I have 17 stores added and available in HA. 
I just added 3 new ones ( to test it) and they also became available in HA.

The 10 stores that are available do they update???
Any errors in the logfile??

**Comment by SteGe88** [comment]
> I guess it's not a limit as I have 17 stores added and available in HA. I just added 3 new ones ( to test it) and they also became available in HA.
> 
> The 10 stores that are available do they update??? Any errors in the logfile??

Hmm okay, that's a bit strange than. All the 10 stores do update, so that is not the problem. Even when I delete the docker (and the files on filesystem) and re-add it, there are only the same 10 known stores appearing.

**Comment by DavyRoswinkel** [comment]
> > I guess it's not a limit as I have 17 stores added and available in HA. I just added 3 new ones ( to test it) and they also became available in HA.
> > The 10 stores that are available do they update??? Any errors in the logfile??
> 
> Hmm okay, that's a bit strange than. All the 10 stores do update, so that is not the problem. Even when I delete the docker (and the files on filesystem) and re-add it, there are only the same 10 known stores appearing.

I have to mention I use the HA addonversion. It could be different...and that could be the problem.

**Comment by MaxWinterstein** [comment]
normally 

https://github.com/MaxWinterstein/toogoodtogo-ha-mqtt-bridge/blob/5ed1ca9d6d683fe5060e0f3a20e89b0ec8e92fa9/toogoodtogo_ha_mqtt_bridge/main.py#L36

should do its job, but I have encountered similar strange things a few days ago.

Will have a look when there is some spare time

**Comment by SteGe88** [comment]
Probably, don't know if that should make any difference. 

I have tried to reconnect one more time, and now I get:
tgtg.exceptions.TgtgAPIError: 429 - Too many requests. Try again later.

So I'm sort off f*cked up now...

**Comment by SteGe88** [comment]
After a full cleanup of the containers and volume, and restart it again, I have now all the favorites in my MQTT broker... Strange but apparently there was something in case or whatever.
