### ISSUE TITLE
Exception in thread Thread-3

### ISSUE THREAD

**Issue by escaflowne62** [MaxWinterstein/toogoodtogo-ha-mqtt-bridge#39]
hello 
first of all thank you for the work provided 
I encounter this error message and I do not know how to solve it

[Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/toogoodtogo_ha_mqtt_bridge/main.py", line 206, in loop
    tgtg_client.login()
  File "/usr/local/lib/python3.8/site-packages/tgtg/__init__.py", line 144, in login
    raise TgtgAPIError("429 - Too many requests. Try again later.")
tgtg.exceptions.TgtgAPIError: 429 - Too many requests. Try again later.]()

**Comment by DavyRoswinkel** [comment]
> hello first of all thank you for the work provided I encounter this error message and I do not know how to solve it
> 
> Exception in thread Thread-3: Traceback (most recent call last): File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner self.run() File "/usr/local/lib/python3.8/threading.py", line 870, in run self._target(*self._args, **self._kwargs) File "/app/toogoodtogo_ha_mqtt_bridge/main.py", line 206, in loop tgtg_client.login() File "/usr/local/lib/python3.8/site-packages/tgtg/**init**.py", line 144, in login raise TgtgAPIError("429 - Too many requests. Try again later.") tgtg.exceptions.TgtgAPIError: 429 - Too many requests. Try again later.

At this moment I am experiencing the same issue. Did it solve by it's self or did you do something to solve this issue???
