### ISSUE TITLE
Exception in thread Thread-3 Please enable JS and disable any ad blocker

### ISSUE THREAD

**Issue by DavyRoswinkel** [MaxWinterstein/toogoodtogo-ha-mqtt-bridge#44]
How to solve this issue??
The addon doesn't start anymore.

```
2022-05-19 10:52:06 [INFO] Connecting mqtt
2022-05-19 10:52:06 [INFO] Starting loop
2022-05-19 10:52:06 [DEBUG] Loaded tokens form tokenfile. Logging in with tokens.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/toogoodtogo_ha_mqtt_bridge/main.py", line 206, in loop
    tgtg_client.login()
  File "/usr/local/lib/python3.8/site-packages/tgtg/__init__.py", line 119, in login
    self._refresh_token()
  File "/usr/local/lib/python3.8/site-packages/tgtg/__init__.py", line 109, in _refresh_token
    raise TgtgAPIError(response.status_code, response.content)
tgtg.exceptions.TgtgAPIError: (403, b'<html><head><title>apptoogoodtogo.com</title><style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style></head><body style="margin:0"><p id="cmsg">Please enable JS and disable any ad blocker</p><script>var dd={\'cid\':\'AHrlqAAAAAMA1QWVrkjdsjgAU_cwAw==\',\'hsh\':\'1D42C2CA6131C526E09F294FE96F94\',\'t\':\'fe\',\'r\':\'b\',\'s\':35560,\'e\':\'20b2d7aefa21836c3426f5986c4ae3fd1116e65ef4b448f7fc259d847f8840d3\',\'host\':\'geo.captcha-delivery.com\'}</script><script src="https://ct.captcha-delivery.com/c.js"></script></body></html>\n
```

**Comment by poudenes** [comment]
Have same issue on:

RPi4
Home Assistant Core 2022.5.5
Home Assistant Supervisor 2022.05.2
Home Assistant OS 8.0
Kernel version 5.15.32-v8
Agent version 1.2.1

**Comment by Florian14490** [comment]
Same issue here.
Will wait patiently for update from maxwinterstein 😊

**Comment by MaxWinterstein** [comment]
Hey everyone, I updated `tgtg-python` to `0.11.3`. This works fine now for me locally, using IPv6, but through docker and IPv4 i am once again blocked 😨 I might have to many instances of this running ;)

Please test and provide feedback!

**Comment by Florian14490** [comment]
Hi Max Winterstein,

Thnx for the update. Addon is back in business.
I appreciate your work.

Have a nice day🤙

**Comment by DavyRoswinkel** [comment]
Hello Max,

Works for me again. Only using IPv4. (Currently blocking IPv6, because of other issue, nothing to do with this addon)
Recently not been blocked by TGTG. 
Maybe you should put a warning in the Readme about the polling schedule.
I use the standard 10 minutes ( in some cases I miss the magic bag) but I never got blocked with this schedule ( I don't know what's a max safe polling_schedule)

Thank for solving this issue, so quickly.
Take care!

**Comment by Florian14490** [comment]
Hi DavyRoswinkel,

I use 1min polling for 5months now. Never blocked (yet). 😛

You were blocked in the past?

**Comment by DavyRoswinkel** [comment]
> Hi DavyRoswinkel,
> 
> I use 1min polling for 5months now. Never blocked (yet). 😛
> 
> You were blocked in the past?

Was blocked in the past, but it was never really clear what was causing this. This was probably caused when TGTG changed the user agent needs.

Will try changing the polling_schedule in some days..( today some upgrades to do on the 3 d printer)

Thanks for sharing your polling_schedule, Florian!

**Comment by poudenes** [comment]
Yes !!! I can run again to the shops to get my stuff!!! Its working again. Thanks for the fast fix!
Interval here every 5 min.
