### ISSUE TITLE
Remove entity for removed stores in tgtg.

### ISSUE THREAD

**Issue by daandav** [MaxWinterstein/toogoodtogo-ha-mqtt-bridge#5]
I really like this integration for tgtg. So thanks for all the good work. However, I noticed that some stores were removed from tgtg in my area (they don't show up in the app's list or on the map anymore). The entities related to those stores are still showing up in the tgtg addon. Maybe it would be nice to remove them when they don't exist anymore to keep things clean?

However, I'm not sure if they really stopped with the tgtg platform, or that they just hid their page for tgtg clients. But some have not shown for over 2 weeks now, so I guess they just stopped. I'm not sure if you can distinguish between a removed shop and hidden shop though.

**Comment by MaxWinterstein** [comment]
Yes, stores that were deactivated (not sure if they show up on the api) are still inside HA. 

I am thinking about some mechanism to keep track of them, and if they are no longer on your favouites (i guess removed stores are not on that api endpoint as well) delete them. 
Quick scrolling over the documentation showed this should be possible: https://www.home-assistant.io/docs/mqtt/discovery/

Will take care of this some day ✌️

**Comment by MaxWinterstein** [comment]
Released v1.4.0

Items will be saved to some local file and when one loop is done, and some saved store is no longer in your favourites, it will send some "autodiscover" message without payload to remove the entitiy from home assistant.

Have a try :)

**Comment by daandav** [comment]
Super nice! This seems to work just fine ;). Thanks!
