### ISSUE TITLE
cannot start ('Settings' object has no attribute 'TGTG' / email)

### ISSUE THREAD

**Issue by prankousky** [MaxWinterstein/toogoodtogo-ha-mqtt-bridge#7]
(please delete)

**Comment by MaxWinterstein** [comment]
don't be shy and delete, your concerns were correct :)

There was a typo in the README, the settings `toogoodtogo` was renamed to `tgtg` a while ago and I missed that in the configuration.

**Comment by prankousky** [comment]
Thank you @MaxWinterstein 
I realized the mistake and thought I messed up the configuration somehow, but I guess it's good I meantioned it after all :) It works perfectly now.
