### ISSUE TITLE
Blocked because of super natural behavior

### ISSUE THREAD

**Issue by poudenes** [MaxWinterstein/toogoodtogo-ha-mqtt-bridge#80]
Hi,

I was checking my normal app on my mobile and im blocked because of super natural use of the application one my external IP.
Reasons:

- supernatural speed of using the app
- something is blocking use of Jasvascript
- There is a robot on same IP that cause this error

I stop and started the add-on and this error I see:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: TooGoodToGo Home Assistant MQTT Bridge
 Publish TooGoodToGo stock as MQTT messages
-----------------------------------------------------------
 Add-on version: 2.3.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 8.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.6.7
 Home Assistant Supervisor: 2022.05.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] toogoodtogo-ha-mqtt-bridge.sh: executing... 
[15:35:46] INFO: Copy settings file
Saved tokens found.
If you have any problems reinstalling the add-on might help.
[cont-init.d] toogoodtogo-ha-mqtt-bridge.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:35:47] INFO: Strating Bridge...
2022-06-30 15:35:52 [INFO] Connecting mqtt
2022-06-30 15:35:52 [INFO] Starting loop
2022-06-30 15:35:52 [INFO] Checking latest tgtg appstore version
2022-06-30 15:35:52 [INFO] Loaded tokens form tokenfile. Logging in with tokens.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/toogoodtogo_ha_mqtt_bridge/main.py", line 288, in fetch_loop
    tgtg_client.login()
  File "/usr/local/lib/python3.8/site-packages/tgtg/__init__.py", line 136, in login
    self._refresh_token()
  File "/usr/local/lib/python3.8/site-packages/tgtg/__init__.py", line 126, in _refresh_token
    raise TgtgAPIError(response.status_code, response.content)
tgtg.exceptions.TgtgAPIError: (403, b'<html><head><title>apptoogoodtogo.com</title><style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style></head><body style="margin:0"><p id="cmsg">Please enable JS and disable any ad blocker</p><script>var dd={\'cid\':\'AHrlqAAAAAMA1dv-1VQTgCIAV9AOyQ==\',\'hsh\':\'1D42C2CA6131C526E09F294FE96F94\',\'t\':\'bv\',\'r\':\'b\',\'s\':35558,\'e\':\'606cf68f2ffad3e8b3053a4d58ae090aa508c798b981ce0d63e3059a071013a1\',\'host\':\'geo.captcha-delivery.com\'}</script><script src="https://ct.captcha-delivery.com/c.js"></script></body></html>\n')
```

**Comment by poudenes** [comment]
The app on mobile is working when im on 4g/5g then there is no problem.
My IP is blocked that's also written in de block massage in the App.

Home Assistant app won't help, because the add-on is installed on RPi and connected via same IP.

In the mobile app I had option to contact them. Asked for removal of the blocking. Told them that I was play with the API and maybe make it to fast with refresh...

**Comment by Dielee** [comment]
@poudenes have you tried to delete tokens.json file from data folder ? 
Maybe tgtg blocks your ua, which is used for logging in at tgtg API. With removing the tokens.js, a new ua would be created.

If your app doesn't work too, you have to change your global IP, or just wait..
There is nothing more we can do at this time.

**Comment by poudenes** [comment]
> tokens.json

Have contact them to remove the block. I can't change the public IP. When I want then maybe my ISP will change it. But there is a lot of things using this IP :) haha...

SO will wait

**Comment by MaxWinterstein** [comment]
yeah, blocking is sadly still a thing and happens to me from time to time. I think it occurred most of the time when I am developing and using multiple add-on instances at once.

 @poudenes might share a screenshot of the error message? I am curious :) 

_Relaxed Mode_ sounds not too bad at all, but managing multiple schedulers is kinda hard. But, maybe a better-defined cron would be something, to begin with.   
Totally untested, but maybe something like [`*/5_4-10_*_*_*`](https://crontab.guru/#*/5_4-10_*_*_*) could help disable polling through the night.  

The logic behind blocking still is a secret to us. Would love to know it...

Lastly, I thought for two years I am unable to get a new IP from my provider, as I have some kind of special contract with them to keep an real IPv4 address in a world where IPv6 dual stack lite is the common. I found that a complete power-reset of the router gets me a new IP 🥳

**Comment by HanBarn** [comment]
@MaxWinterstein 
About scheduling, yes you are right changing the cron can be used to lower the polling frequency during the evening/nightly hours.
The change is more or less fixed because you need to change it manually.
The Intense Fetch overrides the cron if activated manually or by automation.
The same can be done the opposite way for example Relaxed Fetch where the interval and period is in the configuration file the same as Intense Fetch but two extra config lines.
The benefit of such option is the Relaxed Fetch can also be switched on and automated.
This means that only one of the two can be active, Intense or Relaxed Fetch.
It is just a suggestion not a must because the cron can be used too, so it’s is certainly not a priority.
I am not a developer so I don’t know the impact of adding a extra option.
Although I like to limit the amount of request to the TGTG servers to avoid unnecessary load.

About your ISP IP, nice to know if a reset of your router changes the IP.
Most of the time the IP’s are more or less fixed for a long time even if you power down/up the router.
Forcing a new IP might solve your blocking if it happens but it is not a desirable situation for most people because some services are dependent on the IP address like DuckDNS.

I used the Intense Fetch successfully already last Friday.
Sometimes it can be hard to get a TGTG box. 
(still wonder why some boxes are gone within seconds…. inside job? Must be. 😉)

**Comment by poudenes** [comment]
> @poudenes have you tried to delete tokens.json file from data folder ? Maybe tgtg blocks your ua, which is used for logging in at tgtg API. With removing the tokens.js, a new ua would be created.
> 
> If your app doesn't work too, you have to change your global IP, or just wait.. There is nothing more we can do at this time.

Hi What do you mean with delete from data folder. I was searching but can't find any folder data with a tokens.json

I have add a different MAC Address into my router and reboot. Now I can access TGTG again from my phone.
Start the Addon but still get the error:

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/toogoodtogo_ha_mqtt_bridge/main.py", line 288, in fetch_loop
    tgtg_client.login()
  File "/usr/local/lib/python3.8/site-packages/tgtg/__init__.py", line 136, in login
    self._refresh_token()
  File "/usr/local/lib/python3.8/site-packages/tgtg/__init__.py", line 126, in _refresh_token
    raise TgtgAPIError(response.status_code, response.content)
tgtg.exceptions.TgtgAPIError: (403, b'<html><head><title>apptoogoodtogo.com</title><style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style></head><body style="margin:0"><p id="cmsg">Please enable JS and disable any ad blocker</p><script>var dd={\'cid\':\'AHrlqAAAAAMA1dv-1VQTgCIAV9AOyQ==\',\'hsh\':\'1D42C2CA6131C526E09F294FE96F94\',\'t\':\'bv\',\'r\':\'b\',\'s\':35558,\'e\':\'606cf68f2ffad3e8b3053a4d58ae090aa508c798b981ce0d63e3059a071013a1\',\'host\':\'geo.captcha-delivery.com\'}</script><script src="https://ct.captcha-delivery.com/c.js"></script></body></html>\n')
```

**Comment by poudenes** [comment]
Issue solved. After the change of Mac address and new WAN IP, TGTG is working again. Intervals for all to 10min...
