### ISSUE TITLE
Not working anymore...

### ISSUE THREAD

**Issue by DarKOrange75** [MaxWinterstein/toogoodtogo-ha-mqtt-bridge#83]
Hi all,

This add-on was working like a charm for a few month and all of a sudden it stopped working :-(

Log file:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: TooGoodToGo Home Assistant MQTT Bridge
 Publish TooGoodToGo stock as MQTT messages
-----------------------------------------------------------
 Add-on version: 2.3.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 8.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.7.2
 Home Assistant Supervisor: 2022.07.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] toogoodtogo-ha-mqtt-bridge.sh: executing... 
[21:00:40] INFO: Copy settings file
No saved tokens found.
Please make sure to check your email for the login request and answer quickly.
You can't open it on a mobile phone where the TGTG app itself is installed.
[cont-init.d] toogoodtogo-ha-mqtt-bridge.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[21:00:40] INFO: Strating Bridge...
2022-07-10 21:00:43 [INFO] Connecting mqtt
2022-07-10 21:00:43 [INFO] Starting loop
2022-07-10 21:00:43 [INFO] Logging in with credentials
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/toogoodtogo_ha_mqtt_bridge/main.py", line 288, in fetch_loop
    tgtg_client.login()
  File "/usr/local/lib/python3.8/site-packages/tgtg/__init__.py", line 156, in login
    self.start_polling(first_login_response["polling_id"])
  File "/usr/local/lib/python3.8/site-packages/tgtg/__init__.py", line 203, in start_polling
    raise TgtgPollingError(
tgtg.exceptions.TgtgPollingError: Max retries (120 seconds) reached. Try again.

help much appreciated :)

Thank you !

**Comment by HanBarn** [comment]
Did you recently upgraded your Home Assistant version to 2022.7.2 ?
If so, go back to the previous release.
I am on 2022.6.7, no errors.

**Comment by MaxWinterstein** [comment]
```
No saved tokens found.
Please make sure to check your email for the login request and answer quickly.
You can't open it on a mobile phone where the TGTG app itself is installed.
```

Did you click the verification email?

**Comment by DarKOrange75** [comment]
Yes I did. Thank you, I’ll try your solution.

**Comment by DarKOrange75** [comment]
> ```
> No saved tokens found.
> Please make sure to check your email for the login request and answer quickly.
> You can't open it on a mobile phone where the TGTG app itself is installed.
> ```
> 
> 
>      
>   
> 
> Did you click the verification email?

The problem was that TGTG emails were blocked by my mail server… fixed. Thank you !

**Comment by HanBarn** [comment]
> > ```
> > No saved tokens found.
> > Please make sure to check your email for the login request and answer quickly.
> > You can't open it on a mobile phone where the TGTG app itself is installed.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Did you click the verification email?
> 
> 
> The problem was that TGTG emails were blocked by my mail server… fixed. Thank you !

Still strange because you said the Add On worked already for months.
For some reason the tokens have disappeared.

**Comment by DarKOrange75** [comment]
> > > ```
> > > No saved tokens found.
> > > Please make sure to check your email for the login request and answer quickly.
> > > You can't open it on a mobile phone where the TGTG app itself is installed.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Did you click the verification email?
> > 
> > 
> > The problem was that TGTG emails were blocked by my mail server… fixed. Thank you !
> 
> 
> Still strange because you said the Add On worked already for months.
> For some reason the tokens have disappeared.

You are right… I don’t know why.

**Comment by MaxWinterstein** [comment]
So, this still an issue?

**Comment by DarKOrange75** [comment]
No problem is fixed. I close this ticket.
