### ISSUE TITLE
Error starting Add On

### ISSUE THREAD

**Issue by HanBarn** [MaxWinterstein/toogoodtogo-ha-mqtt-bridge#87]
Today I have noticed the Too Good To Go addon integration failed.
Until today I had no issues at all for weeks.
I did not update HA yet to the latest version.

I did made a small change using the TGTG app, I have added two new favorite stores, that’s all.
I can remove them to reproduce the error but new entries should not give any issues.

I did restart the Addon, no change.
I did not restart HA, because it is running fine for some time now. A restart is possible.

Log:

[17:18:31] INFO: Strating Bridge...
2022-08-18 17:18:32 [INFO] Connecting mqtt
2022-08-18 17:18:32 [INFO] Starting loop
2022-08-18 17:18:32 [INFO] Checking latest tgtg appstore version
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/toogoodtogo_ha_mqtt_bridge/main.py", line 287, in fetch_loop
    token_exits = check_existing_token_file()
  File "/app/toogoodtogo_ha_mqtt_bridge/main.py", line 205, in check_existing_token_file
    return read_token_file()
  File "/app/toogoodtogo_ha_mqtt_bridge/main.py", line 223, in read_token_file
    if not is_latest_version():
  File "/app/toogoodtogo_ha_mqtt_bridge/main.py", line 174, in is_latest_version
    minor_diff = act_version.minor - token_version.minor
AttributeError: 'LegacyVersion' object has no attribute 'minor'

**Comment by MaxWinterstein** [comment]
Might share the stores with me? 

Seen something like this before, where they hat problematic attributes.

**Comment by HanBarn** [comment]
It is actually one (new) store offering two different kind of boxes.
http://share.toogoodtogo.com/item/840433
The strange thing is the second box entity in HA does not return any status.
So no ID in the URL link.
Maybe this is the cause of the error.
I can remove the second entity.
In the TGTG app two boxes are showing correctly, two different prices too.

**Comment by DavyRoswinkel** [comment]
I have the same error with no new stores. 
Yesterday morning everything was okay. This morning the addon give the same error:
2022-08-19 09:38:37 [INFO] Checking latest tgtg appstore version
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/toogoodtogo_ha_mqtt_bridge/main.py", line 287, in fetch_loop
    token_exits = check_existing_token_file()
  File "/app/toogoodtogo_ha_mqtt_bridge/main.py", line 205, in check_existing_token_file
    return read_token_file()
  File "/app/toogoodtogo_ha_mqtt_bridge/main.py", line 223, in read_token_file
    if not is_latest_version():
  File "/app/toogoodtogo_ha_mqtt_bridge/main.py", line 174, in is_latest_version
    minor_diff = act_version.minor - token_version.minor
AttributeError: 'LegacyVersion' object has no attribute 'minor'

**Comment by DavyRoswinkel** [comment]
Great idea, It deletes the token.
So you can get a fresh token...
Problem...solved!

**Comment by HanBarn** [comment]
The AddOn was running fine until today.
I have changed the polling schedule which usually restarts the AddOn.
This time the restart caused the same errors again as mentioned before.
So it looks like something is wrong there.
Again the AddOn have to be removed and reinstalled.
The token file has to be added again by accepting the email.
Not sure if I can reproduce the error, need to change the polling schedule again later today.
Previously the polling schedule could be change at any time, a restart did not cause any problems.
Mabybe @DavyRoswinkel can do some checks too by changing the schedule.

**Comment by MaxWinterstein** [comment]
Just did a quick dive through that section of the code, but yes, is is broken.

If there is an existing token then some version check is performed. Sadly the google-play-scraper does not return a valid version anymore, just

![image](https://user-images.githubusercontent.com/5927148/185744548-ca7dd1fa-7d8e-4583-919d-0d9c4f7b04e7.png)

which leaks to the mentioned error above: 

```python
File "/app/toogoodtogo_ha_mqtt_bridge/main.py", line 174, in is_latest_version
minor_diff = act_version.minor - token_version.minor
AttributeError: 'LegacyVersion' object has no attribute 'minor'
```

As no requirements where changed I guess there is some magic possible like
"Some old android device gets version foo, a recent one version bar" - which at least would expain the message: `Varies with device`

I will do some research 👍

**Comment by MaxWinterstein** [comment]
Aaaaand there we have it: https://github.com/JoMingyu/google-play-scraper/issues/144

Will merge #89 and try to bake a release asap, not sure if I can do it now, running out of time here...

**Comment by MaxWinterstein** [comment]
![image](https://user-images.githubusercontent.com/5927148/185744906-c5dc39e4-8be7-40c1-8546-2007d440d70c.png)

Works, but will still be broken for existing tokens that contain that faulty string.

**Comment by MaxWinterstein** [comment]
Note for later me: https://github.com/ahivert/tgtg-python/commit/cc58615dcda184e3ac7619233a1cda2e319085f6

**Comment by MaxWinterstein** [comment]
Update to 2.4.0 is available, sadly HomeAssistantAddon release tool seems broken, can't build for now :(

**Comment by HanBarn** [comment]
I see the new 2.4.0 in HA but the update failed.
Do you mean this error in HA?

22-08-20 16:15:15 ERROR (SyncWorker_3) [supervisor.docker.interface] Can't install maxwinterstein/homeassistant-addon-toogoodtogo-ha-mqtt-bridge-amd64:2.4.0: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=2.4.0&fromImage=maxwinterstein%2Fhomeassistant-addon-toogoodtogo-ha-mqtt-bridge-amd64&platform=linux%2Famd64: Not Found ("manifest for maxwinterstein/homeassistant-addon-toogoodtogo-ha-mqtt-bridge-amd64:2.4.0 not found: manifest unknown: manifest unknown")

(accidentally closed the case… sorry)

**Comment by MaxWinterstein** [comment]
> I see the new 2.4.0 in HA but the update failed. Do you mean this error in HA?
> 
> 22-08-20 16:15:15 ERROR (SyncWorker_3) [supervisor.docker.interface] Can't install maxwinterstein/homeassistant-addon-toogoodtogo-ha-mqtt-bridge-amd64:2.4.0: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=2.4.0&fromImage=maxwinterstein%2Fhomeassistant-addon-toogoodtogo-ha-mqtt-bridge-amd64&platform=linux%2Famd64: Not Found ("manifest for maxwinterstein/homeassistant-addon-toogoodtogo-ha-mqtt-bridge-amd64:2.4.0 not found: manifest unknown: manifest unknown")
> 
> (accidentally closed the case… sorry)

Yes. Will try to fix it later or tomorrow, needed to leave for now…

**Comment by MaxWinterstein** [comment]
Update should now be available. Pls try again :)

GitHub action (aka. Build pipeline) was broken. Need to overhaul this process in total, one day, when I win the time lottery and can work on all my stuff……

**Comment by HanBarn** [comment]
The update is running fine now!
Thanks for your time and action.
